# Generated by Django 5.1.4 on 2024-12-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('users', '0004_buyer_seller_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.buyer'),
        ),
    ]
