services:

  app-agricola-comprador:
    stdin_open: true
    tty: true
    command: bash
    build:
      context: ./frontend/app-agricola-comprador
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./frontend/app-agricola-comprador/app-agricola-comprador:/home/app-agricola-comprador

  # app-agricola-vendedor:
  #   stdin_open: true
  #   tty: true
  #   command: bash
  #   build:
  #     context: ./frontend/app-agricola-vendedor
  #   ports:
  #     - "19003:19000"
  #     - "19004:19001"
  #     - "19005:19002"
  #     - "8083:8081"
  #     - "8084:8082"
  #   volumes:
  #     - ./frontend/app-agricola-vendedor/app-agricola-vendedor:/home/app-agricola-vendedor

  # backend:
  #   stdin_open: true
  #   tty: true
  #   command: bash
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend/app-agricola/:/home/app-agricola
