# Generated by Django 5.1.4 on 2024-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Vendedor'), ('buyer', 'Comprador')], default='buyer', max_length=10),
        ),
    ]
