# Generated by Django 5.1.4 on 2024-12-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_buyer_seller_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
